### ISSUE TITLE
Remove custom external styling being applied to internal Perseus components

### ISSUE THREAD

**Issue by jamalex** [learningequality/kolibri-exercise-perseus-plugin#16]
See discussion at: https://github.com/learningequality/kolibri-exercise-perseus-plugin/pull/13/files#r87825264

**Comment by rtibbles** [comment]
Fixed in #31 .

**Comment by indirectlylit** [comment]
there's still a fair amount of custom injected styling under the `#perseus` id

**Comment by rtibbles** [comment]
Fair enough, we can keep looking at cleaning it up.

**Comment by rtibbles** [comment]
It's as limited as it's going to get:

https://github.com/learningequality/kolibri-exercise-perseus-plugin/blob/master/kolibri_exercise_perseus_plugin/assets/src/views/index.vue#L470
