### ISSUE TITLE
Rename to kolibri-plugin-perseus

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri-exercise-perseus-plugin#174]
For the purpose of having consequently named plugins like `kolibri-plugin-*`, could we rename this as:

`kolibri-plugin-perseus`

Or something similar? Suggestions?

Since it's only currently distributed and then bundled into Kolibri, I think it's easy to change.

I a very speculative and unlikely future, we could see `kolibri-plugin-perseus-legacy` or `kolibri-plugin-perseus2.1` or `kolibri-plugin-perseus-with-a-funny-theme`. I doubt it.

But the main thing would just be to make external plugins easily searchable, visible and package-able.

Suggesting to: Discuss this briefly, and close this issue if we decide that it's not worth it.

**Comment by benjaoming** [comment]
(this was opened because we are adding 2 more external plugins)

**Comment by rtibbles** [comment]
Closing as wontfix.
