### ISSUE TITLE
Keypad is appearing in exam report for input type on tablet.

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri-exercise-perseus-plugin#183]
### Observed behavior
When learner click on "Show correct answer" checkbox in exam report, it opens keypad. 

### Expected behavior
It must not open keypad.

### Steps to reproduce
1. login with learner using tablet.
2. Submit the exam which is having input type question.
3. Click on exam report on tablet and go to the input type question.
4. Click on Show correct answer.

### Context
 * Kolibri version : Kolibri 0.11.0
 * Operating system : Ubuntu 14.04
 * Browser : chrome

![img_20190107_143731](https://user-images.githubusercontent.com/12776071/50966870-5ad91100-14fc-11e9-9f46-f06e321751f4.jpg)

**Comment by rtibbles** [comment]
I think this should just be a matter of unfocusing the input box after we have set the correct answer in it. Will need to be fixed on the Kolibri Perseus Renderer Repo.

**Comment by rtibbles** [comment]
Fixed in #184
