### ISSUE TITLE
Image sizes within Perseus exercises should not be getting set externally by plugin

### ISSUE THREAD

**Issue by jamalex** [learningequality/kolibri-exercise-perseus-plugin#30]
The following styling:

![image](https://cloud.githubusercontent.com/assets/618416/22865862/ff55167c-f120-11e6-9b74-530f993cdfda.png)

Makes small images blow up to this:

![image](https://cloud.githubusercontent.com/assets/618416/22865860/ec3a305e-f120-11e6-842f-4e8cfa2853ca.png)

Disabling this styling fixes this, and then they look like this:
![image](https://cloud.githubusercontent.com/assets/618416/22865868/1f324456-f121-11e6-9d19-e71c65147656.png)

**Comment by jamalex** [comment]
(Probably we want to keep some sort of `max-width`, both in terms of pixels and %, but not set a `height` or `width`)

**Comment by 66eli77** [comment]
@jamalex will replace `width` and `height` with `max-width:100%` solve the issue? if you tell me the channel id, I can test it from my machine.

**Comment by 66eli77** [comment]
also if you can give the channel name/id and the issue exercise name would be much helpful.

**Comment by 66eli77** [comment]
issue exercise: http://localhost:8000/learn/#/learn/1d8f6d84618153c18c695d85074952a7/content/459628b329625ca7880445330885f31d

solution:
#perseus img {
    max-width: 100%;
    padding: 10px;
    vertical-align: middle;
}
