### ISSUE TITLE
Unescaped $ causes text formating issue

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri-exercise-perseus-plugin#36]
@jamalex I'm not sure if this is the right repo to post the issue, but we can move it any time.

CK-12 exercise: 
`Math > Elementary Math > Grade 2 > Addition and Subtraction > Addition and Subtraction to 1,000: Word Problems Subtracting 3 Numbers - Word Problems`
Subtracting 3 Numbers - Word Problems 

https://instantschools.learningequality.org/learn/#/topics/1d8f6d84618153c18c695d85074952a7/content/59f300d96d2358c0abdf9289495e69c7

<img width="1318" alt="subtracting_3_numbers_-_word_problems_practice_-_ck-12_-_kolibri_-__navegacio_privada_" src="https://cloud.githubusercontent.com/assets/1457929/23128938/08503a20-f781-11e6-9a7b-6262ff874b8d.png">

I probably wouldn't dwell on it too much had I not seen that the span in question had an `aria-hidden` attribute, and I couldn't figure out why, in the context of the exercise itself:

<img width="1965" alt="subtracting_3_numbers_-_word_problems_practice_-_ck-12_-_kolibri_2" src="https://cloud.githubusercontent.com/assets/1457929/23129121/c7ce135e-f781-11e6-8690-f6ac6692ce81.png">

My guess is that the `$` char in front of 74 and/or 24 was not properly escaped and is wrecking havoc on the formatting...

**Comment by jamalex** [comment]
Thanks! You're exactly right. Perseus uses $ to surround Mathjax (Latex) code. I'll look into how best to escape them.

**Comment by jamalex** [comment]
Should be fixed in https://github.com/fle-internal/sushi-chef-ck12/pull/1/commits/2618426b9328ddb6520e22a4a515cf8852d9ba9e

(we can confirm and close this in a couple of days, once the channel's been updated)

**Comment by radinamatic** [comment]
Ok, waiting for the updated channel to re-test! :+1:
