### ISSUE TITLE
Images missing in exercises Instant Schools Math

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri-exercise-perseus-plugin#37]
`Instant School Math > Early math > Counting > Counting small numbers`

https://instantschools.learningequality.org/learn/#/topics/11d9de56da744f98877cc9fe710bb78d/content/9cefc3c618da41c79861df2a29ad8c9f

![count with small numbers - instant schools math - kolibri - google chrome_058](https://cloud.githubusercontent.com/assets/1457929/23134542/7eaa2aa0-f795-11e6-850d-16b797e9cfe1.png)

`Instant School Math > Early math > Counting > Count in order`

https://instantschools.learningequality.org/learn/#/topics/11d9de56da744f98877cc9fe710bb78d/content/656259fb21bb40d494a9931148d35e21

![count in order - instant schools math - kolibri - google chrome_059](https://cloud.githubusercontent.com/assets/1457929/23134712/156cc57e-f796-11e6-85b5-44e97d23b89d.png)

`Instant School Math > Early math > Counting > Find 1 more or 1 less than a number`

https://instantschools.learningequality.org/learn/#/topics/11d9de56da744f98877cc9fe710bb78d/content/44d60f677fa04938afdba9807e46b8ea

![find 1 more or 1 less than a number - instant schools math - kolibri - google chrome_060](https://cloud.githubusercontent.com/assets/1457929/23134827/8265d4f4-f796-11e6-8cf2-8b0a980a9762.png)

`Instant School Math > Early math > Counting > Numbers 0 to 120`

https://instantschools.learningequality.org/learn/#/topics/11d9de56da744f98877cc9fe710bb78d/content/678f22a8bfec4f5bb4969d0817a23499

![numbers to 100 - instant schools math - kolibri - google chrome_061](https://cloud.githubusercontent.com/assets/1457929/23134942/f6b60f04-f796-11e6-8a63-b7aaa585d2dd.png)

I'm guessing this is a general point, so switching channels for the time being... :stuck_out_tongue: 

![add within 5 - instant schools math - kolibri - google chrome_062](https://cloud.githubusercontent.com/assets/1457929/23135083/788b7ec4-f797-11e6-9515-ec1a8e697094.png)

**Comment by rtibbles** [comment]
Not a rendering issue.
