### ISSUE TITLE
ReferenceError: KAS is not defined

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri-exercise-perseus-plugin#38]
`Instant School Math > Geometry > Volume and surface area > Volume of cones, cylinders, and spheres`

https://instantschools.learningequality.org/learn/#/topics/11d9de56da744f98877cc9fe710bb78d/topic/9df74b3a1210411e96f7e7995441c2ee

![volumes of cones cylinders and spheres - instant schools math - kolibri - google chrome_064](https://cloud.githubusercontent.com/assets/1457929/23135246/2073c5e2-f798-11e6-86e2-da8ac286735d.png)

**Comment by radinamatic** [comment]
Same error in: `Instant School Math > Geometry > Volume and surface area > Solid geometry`

https://instantschools.learningequality.org/learn/#/topics/11d9de56da744f98877cc9fe710bb78d/content/438ce80262124bf28f78678cb422cfba

![solid geometry - instant schools math - kolibri - google chrome_065](https://cloud.githubusercontent.com/assets/1457929/23135637/b1516bfe-f799-11e6-98e2-913ed4d336ee.png)

**Comment by radinamatic** [comment]
`Instant School Math > Geometry > Analytic geometry > Challenge: Distance between a point and a line`

https://instantschools.learningequality.org/learn/#/topics/11d9de56da744f98877cc9fe710bb78d/content/484dd0ab20a24dfcaafbc58c6df2e790

![distance between point line - instant schools math - kolibri - google chrome_066](https://cloud.githubusercontent.com/assets/1457929/23135759/1f946efe-f79a-11e6-96bb-ce4febfcdc8c.png)

**Comment by radinamatic** [comment]
More exercises with the same error:

https://instantschools.learningequality.org/learn/#/topics/11d9de56da744f98877cc9fe710bb78d/content/1388567715b848b8b48029d940f57f87

https://instantschools.learningequality.org/learn/#/topics/11d9de56da744f98877cc9fe710bb78d/content/d4618dae6dae49beb8afe2566f9fd542

https://instantschools.learningequality.org/learn/#/topics/11d9de56da744f98877cc9fe710bb78d/content/f07c89a496354bb884d0fe07965dde80

https://instantschools.learningequality.org/learn/#/topics/11d9de56da744f98877cc9fe710bb78d/content/fea2f320d35c4ba286f1233e2742d47b

https://instantschools.learningequality.org/learn/#/topics/11d9de56da744f98877cc9fe710bb78d/content/b84b0eb6885944bca39f5aaaee18d28e

**Comment by rtibbles** [comment]
This is exactly why having someone awesome doing QA is so important!

I know how to fix this, thanks for finding it!

**Comment by radinamatic** [comment]
Not enough blush in this emoji... :blush:  :blush:  :blush:
