### ISSUE TITLE
Static resources with incorrect (local) links do not load

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri-exercise-perseus-plugin#39]
@ralphiee22 Some of the local references for images might have persisted when you built the Math channel? 

![draw rays lines line segments - instant schools math - kolibri - google chrome_072](https://cloud.githubusercontent.com/assets/1457929/23170871/0f376ad6-f851-11e6-8850-c86c36bd4048.png)

https://instantschools.learningequality.org/learn/#/topics/11d9de56da744f98877cc9fe710bb78d/content/8e41ad43ee824e308b4714de161ab36a

cc @jayoshih

**Comment by rtibbles** [comment]
Not a renderer issue.
