### ISSUE TITLE
question not loading

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-exercise-perseus-plugin#45]
![image](https://cloud.githubusercontent.com/assets/2367265/23722746/5fb5d41a-03fb-11e7-875d-1b28203b2c2f.png)

https://instantschools.learningequality.org/learn/#/topics/1d8f6d84618153c18c695d85074952a7/content/cd63bb218a9a5a3799805057e86b7051

migrated from: https://trello.com/c/iZ5sp4wp/16-exercises-ck-12-exercise-question-not-loading

**Comment by rtibbles** [comment]
This is due to malformed JSON, content issue.

**Comment by rtibbles** [comment]
Migrated to here: https://trello.com/c/iZ5sp4wp/16-exercises-ck-12-exercise-question-not-loading

**Comment by jamalex** [comment]
This actually looks to be a Perseus export issue (see comment on Trello card); migrating to:

https://trello.com/c/Ke2MrknT/284-slashes-not-being-properly-escaped-during-perseus-export
