### ISSUE TITLE
need better wording depending on available hints

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-exercise-perseus-plugin#46]
'No More Hints' appears on questions without hints

![image](https://cloud.githubusercontent.com/assets/2367265/23722803/9dadc8d6-03fb-11e7-8360-7f532421bcf1.png)

migrated from https://trello.com/c/iOx9Up1D/26-no-more-hints-appears-on-questions-without-hints

**Comment by rtibbles** [comment]
Fixed.
