### ISSUE TITLE
Exercises: CK-12 'next question' button not functional

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-exercise-perseus-plugin#47]
see e.g.

https://instantschools.learningequality.org/learn/#/topics/1d8f6d84618153c18c695d85074952a7/content/d260d44310115bd699c7d70c8d063d53

migrated from https://trello.com/c/Xg19KUnf/20-exercises-ck-12-next-question-button-not-functional

**Comment by rtibbles** [comment]
N.B. the above link does not load :/

**Comment by indirectlylit** [comment]
the instantschools link? odd - it does for me

**Comment by rtibbles** [comment]
Oh weird, it shows up now. Gave me an error first time!

**Comment by rtibbles** [comment]
Also, 'next question' appears to be working now. I think this may have been fixed already by @66eli77.

**Comment by rtibbles** [comment]
Fixed here by @christianmemije https://github.com/learningequality/kolibri-exercise-perseus-plugin/pull/34
