### ISSUE TITLE
text formatting issue

### ISSUE THREAD

**Issue by jeepurs** [learningequality/kolibri-exercise-perseus-plugin#48]
## Description

Exercise text is not showing correctly. It sometimes looks like this:

![image001](https://cloud.githubusercontent.com/assets/5150483/23815115/60f6c932-059b-11e7-9b96-0e81ab483c29.png)

But it should look like this:

![image](https://cloud.githubusercontent.com/assets/2367265/23815586/89d1555a-059d-11e7-92fb-342dc5ea9ead.png)

## Steps to reproduce

Not always reproducible, but sometimes visible on Chrome

* Exercises link: 
https://instantschools.learningequality.org/learn/#/topics/11d9de56da744f98877cc9fe710bb78d/content/678f22a8bfec4f5bb4969d0817a23499
* Error shown, before refreshing exercise page:  
https://instantschools.learningequality.org/api/content/1d8f6d84618153c18c695d85074952a7/contentnode/678f22a8bfec4f5bb4969d0817a23499/?1489174966936=1489174966936
* No error upon refresh: https://instantschools.learningequality.org/api/content/11d9de56da744f98877cc9fe710bb78d/contentnode/678f22a8bfec4f5bb4969d0817a23499/?1489175020039=1489175020039

## Additional Info

Note: channel ID's are different upon refresh. Maybe a clue?

**Comment by rtibbles** [comment]
No fresh reports, closing.
