### ISSUE TITLE
Error loading font (possibly due to Mathjax)

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri-exercise-perseus-plugin#72]
`Access to Font at 'about:blank' from origin 'http://127.0.0.1:8000' has been blocked by CORS policy: Invalid response. Origin 'http://127.0.0.1:8000' is therefore not allowed access.`

![image](https://cloud.githubusercontent.com/assets/1680573/25565108/18b7f40e-2d76-11e7-80c8-543fcc5e12d8.png)

**Comment by DXCanas** [comment]
Pretty sure we figured this out. They're using it to make sure they can test for errors properly
