### ISSUE TITLE
Mock i18n functionality for text internal to the Perseus renderer

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri-exercise-perseus-plugin#90]
Currently any text internal to Perseus reaches out to the `i18n._` method, which has no access to any translation strings - also, we do not include the appropriate strings from the KA Crowdin to enable this.

**Comment by jeepurs** [comment]
Another example of unwrapped strings:
![image](https://user-images.githubusercontent.com/5150483/27601212-5fb3180e-5b23-11e7-9138-a1182c40846b.png)

Note that the inline description text exists for both answer boxes.

**Comment by jeepurs** [comment]
Example of another exercise with same issue:  
![image](https://user-images.githubusercontent.com/5150483/27747612-bc372afc-5d80-11e7-9c90-e54b663349d9.png)

**Comment by jeepurs** [comment]
Another example of exercise with same issue, but the phrase is "None of the above".  Must answer a few questions before you come across a suitable example: https://sw-instantschools.learningequality.org/learn/#/topics/93a5bfcfa2a74962be843288aefcfc0e/content/04adf811ca204f31845d125a55a00d1e

![image](https://user-images.githubusercontent.com/5150483/27932850-185164c4-6254-11e7-81b0-81321e045f24.png)

**Comment by rtibbles** [comment]
Fixed in #99
