### ISSUE TITLE
image formatting issues - labels are offset

### ISSUE THREAD

**Issue by jeepurs** [learningequality/kolibri-exercise-perseus-plugin#91]
KA exercises that contain Images with labels are offset from each other. Example below:

![image](https://user-images.githubusercontent.com/5150483/27161121-131f8ca6-512e-11e7-8d54-074ed2751bce.png)

(and link on demo site provided here: https://sw-instantschools.learningequality.org/learn/#/topics/93a5bfcfa2a74962be843288aefcfc0e/content/b63a3d78f693415b8ebf29782980c132)

For reference, there are two other open issues that may be related:
-Filed by @radinamatic in Feb: https://github.com/learningequality/kolibri-exercise-perseus-plugin/issues/37
-Filed by me in Mar: https://github.com/learningequality/kolibri-exercise-perseus-plugin/issues/48

**Comment by rtibbles** [comment]
This is probably fixed by work done on styling by @DXCanas. This fix is in the 0.6.x renderer series, currently used in Kolibri 0.4.x.

**Comment by rtibbles** [comment]
Pretty sure this is now fixed, please reopen if it recurs in a newer version.
