### ISSUE TITLE
Broken json results in incomplete exercises

### ISSUE THREAD

**Issue by jeepurs** [learningequality/kolibri-exercise-perseus-plugin#93]
First exercise example:

![image](https://user-images.githubusercontent.com/5150483/27161258-0dd969d2-512f-11e7-8160-bc3cbe9f0c0b.png)

Second exercise example:

![image](https://user-images.githubusercontent.com/5150483/27161270-1e811078-512f-11e7-9a38-f69a66223222.png)

Link to exercises on demo site:
https://sw-instantschools.learningequality.org/learn/#/topics/93a5bfcfa2a74962be843288aefcfc0e/content/d739824261334d6183dfa897779b6007

https://sw-instantschools.learningequality.org/learn/#/topics/93a5bfcfa2a74962be843288aefcfc0e/content/b22f4a022c1b4d23af4e091433396b55

Notes from @ralphiee22:  one exercise has images, and they are present, but cant be rendered due to json. the other exercise does not use any images, and cant be rendered due to json

**Comment by rtibbles** [comment]
Not sure why this is opened here - this is due to badly formed json being passed into the renderer. If I recall correctly this was because parts of the json that should not be translated on KA's translation platform was translated, it should be fixed there.

**Comment by indirectlylit** [comment]
Should we possibly add graceful user-facing failure handling? I think in some other places you have a "could not render exercise" message

**Comment by rtibbles** [comment]
If perseus errors out we do that, however, in these cases perseus throws no
errors, because the json is valid, but the translated text make it fail to
completely render.

**Comment by rtibbles** [comment]
Might have something to do with this: https://sw-instantschools.learningequality.org/zipcontent/c33836cf695e5fefd265a0768f4a25a9.perseus/fc9bb413124d50f0a2735f6cc6b77756.json

@ralphiee22 `url: "web+graphie:file:///data/ka-sushi-chef-sw/build/670/6706a006f4f7987bbbc55a793202e422dd097fcc"` seems to be pointing to an invalid file path.

**Comment by rtibbles** [comment]
And to confirm again, the second exercise you report is because the string 'improper' was translated, this should not be translated, and it's not clear to either me or @ralphiee22 how it got translated, but it needs to be fixed in the KA translations.

**Comment by ralphiee22** [comment]
@rtibbles yeah that is on my TODO to fix for that invalid file path. Going to fix today, and that should be the last error on my side.
